[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "pyasyncproxy"
readme = "README.md"
dynamic = ["version"]
requires-python = ">=3.12"
description = "The asynchronous network proxy application."
authors = [
  { name = "zlhywlf", email = "tommietanghao@zlhywlf.onmicrosoft.com" },
]
classifiers = [
  "Framework :: AsyncIO",
  "Framework :: Pydantic",
  "Environment :: Web Environment",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "gunicorn~=23.0.0;sys_platform!='win32'",
  "httpx~=0.27.0",
  "pydantic~=2.8.0",
  "pydantic-settings~=2.4.0",
  "starlette~=0.38.0",
  "uvicorn~=0.30.0",
  "psutil~=6.0.0",
]

[project.urls]
"Homepage" = "https://github.com/zlhywlf/pyasyncproxy"

[project.scripts]
pyasyncproxy = "pyasyncproxy.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["src/pyasyncproxy"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/pyasyncproxy/_version.py"
template = """
# file generated by setuptools_scm
# don't change, don't track in version control

version = {version!r}
version_tuple = {version_tuple!r}

"""

[tool.ruff]
line-length = 120
fix = true
preview = true
exclude = ["src/pyasyncproxy/_version.py"]

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"

[tool.ruff.lint]
select = [
  "A", "ANN", "ARG", "ASYNC", "B", "BLE", "C4", "COM", "CPY", "D", "DTZ", "E", "EM", "ERA", "F", "FBT", "I", "ICN",
  "ISC", "N", "PIE", "PT", "PTH", "PYI", "Q", "RET", "RSE", "RUF", "S", "SIM", "SLOT", "T20", "TD", "UP", "W",
]
ignore = ["COM812", "D203", "D213", "ISC001", "RUF029"]

[tool.ruff.lint.extend-per-file-ignores]
"test_*.py" = ["S101"]
"__init__.py" = ["D104", "CPY001"]
"src/pyasyncproxy/*" = ["N999"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]

[tool.pytest_env]
PROXY_DEBUG = true

[tool.mypy]
strict = true
python_version = "3.12"
files = ["src/pyasyncproxy", "tests"]

[[tool.mypy.overrides]]
module = []
ignore_missing_imports = true

[tool.coverage.report]
exclude_also = [
  "if __name__ == .__main__.:",
  "@(abc\\.)?abstractmethod",
]
omit = [
  "src/pyasyncproxy/_version.py",
  "tests/*",
]
